version: "3.9"
services:
  application-1:
    container_name: DDOMTI-1
    image: localhost:5000/ddomti:latest
    stdin_open: true
    ports:
      - "12000:12000"
    environment:
      - server_port=12000
      - spring_data_mongodb_host=mongo
      - p2p_endpoint=http://p2p-1:12001
      - p2p_port=50601
      - connection_host=p2p-1
      - connection_port=50601
      - identity_file_path=identities/IdentityRegister-Port-Operator.json
    depends_on:
      mongo:
        condition: service_started
      p2p-1:
        condition: service_started

  p2p-1:
    container_name: P2P-1
    image: localhost:5000/p2p:latest
    restart: always
    ports:
      - "12001:12001"
      - "50601:50601"
    environment:
      - server_port=12001
      - p2p_name=peer-1
      - p2p_port=50601

  application-2:
    container_name: DDOMTI-2
    image: localhost:5000/ddomti:latest
    restart: always
    stdin_open: true
    ports:
      - "12002:12002"
    environment:
      - server_port=12002
      - spring_data_mongodb_host=mongo
      - p2p_endpoint=http://p2p-2:12003
      - p2p_port=50602
      - connection_host=p2p-1
      - connection_port=50601
      - identity_file_path=identities/IdentityRegister-VTS-Operator.json
    depends_on:
      mongo:
        condition: service_started
      p2p-2:
        condition: service_started

  p2p-2:
    container_name: P2P-2
    image: localhost:5000/p2p:latest
    restart: always
    ports:
      - "12003:12003"
      - "50602:50602"
    environment:
      - server_port=12003
      - p2p_name=peer-2
      - p2p_port=50602

  application-3:
    container_name: DDOMTI-3
    image: localhost:5000/ddomti:latest
    restart: always
    stdin_open: true
    ports:
      - "12004:12004"
    environment:
      - server_port=12004
      - spring_data_mongodb_host=mongo
      - p2p_endpoint=http://p2p-3:12005
      - p2p_port=50603
      - connection_host=p2p-1
      - connection_port=50601
      - identity_file_path=identities/IdentityRegister-Vessel.json
    depends_on:
      mongo:
        condition: service_started
      p2p-3:
        condition: service_started

  p2p-3:
    container_name: P2P-3
    image: localhost:5000/p2p:latest
    restart: always
    ports:
      - "12005:12005"
      - "50603:50603"
    environment:
      - server_port=12005
      - p2p_name=peer-3
      - p2p_port=50603

  mongo:
    container_name: MongoDB
    image: mongo:6.0.1
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo-data:/data/db
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin

volumes:
  mongo-data:
    driver: local